#!/bin/bash

# Get the directory of the current script and cd into it.
SOURCE_DIR="$(dirname "$(realpath "$0")")"
export ENV_DEV="$SOURCE_DIR/.."
echo "export ENV_DEV=$ENV_DEV" >> ~/.bashrc
cd "$SOURCE_DIR"

# setup private environments and log errors.
./private_environments 2>> "$ENV_DEV/error.log"

# run through local environment setup and log errors.
setup/git 2>> "$ENV_DEV/error.log"
setup/gh  2>> "$ENV_DEV/error.log"
setup/dotfile ".vimrc" 2>> "$ENV_DEV/error.log"
