#!/bin/bash

# Check kernel name
case "$(uname -s)" in
  Linux*)
    machine="Linux"
    ;;
  Darwin*)
    # macOS, iOS, etc.
    machine="Darwin"
    ;;
  *)
    machine="Other"
esac

# Check bit
case "$(uname -i)" in
  x86_64*)
    bit="64"
    ;;
  i386*)
    bit="32"
    ;;
  *)
    bit="Other"
esac

if [ "$machine" != "Linux" ] && [ "$machine" != "Darwin" ]
then
  >&2 echo "$(date +%D) $(date +%T) ERROR $machine is not supported at this time"
  exit 1
fi

NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# if brew is not in the PATH, add it
if ! command -v brew &> /dev/null
then
  echo "$(date +%D) $(date +%T) INFO attempting to add brew to path" >> error.log
  if [ "$machine" == "Linux" ]
  then
    (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> $HOME/.bashrc
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  elif [ "$machine" == "Darwin" ]
  then
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zshrc
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
fi

# if brew is not in the PATH, it failed to install
if ! command -v brew &> /dev/null
then
  >&2 echo "$(date +%D) $(date +%T) ERROR brew command failed to install"
  exit 1
fi

exit 0
