#!/bin/bash

# Check kernel name
case "$(uname -s)" in
  Linux*)
    machine="Linux"
    ;;
  Darwin*)
    # macOS, iOS, etc.
    machine="Darwin"
    ;;
  *)
    machine="Other"
esac

if [ "$machine" != "Linux" ]
then
  >&2 echo "$(date +%D) $(date +%T) ERROR $machine is not supported at this time"
  exit 1
fi

if ! command -v apt &> /dev/null
then
  >&2 echo "$(date +%D) $(date +%T) ERROR only supports apt package manager at this time"
  exit 1
fi

# if command exists this is also how you update it
sudo apt update
sudo apt -y install neovim

if ! command -v nvim &> /dev/null
then
  >&2 echo "$(date +%D) $(date +%T) ERROR neovim failed to installed"
  exit 1
fi

exit 0
