#!/bin/bash

# Check kernel name
case "$(uname -s)" in
  Linux*)
    machine="Linux"
    ;;
  Darwin*)
    # macOS, iOS, etc.
    machine="Darwin"
    ;;
  *)
    machine="Other"
esac

# Check bit
case "$(uname -i)" in
  x86_64*)
    bit="64"
    ;;
  i386*)
    bit="32"
    ;;
  *)
    bit="Other"
esac

if [ "$machine" != "Linux" ] && [ "$machine" != "Darwin" ]
then
  >&2 echo "$(date +%D) $(date +%T) ERROR $machine is not supported at this time"
  exit 1
fi

if ! command -v dpkg &> /dev/null
then
  >&2 echo "$(date +%D) $(date +%T) ERROR only supports deb packages at this time"
  exit 1
fi

if [ "$bit" != "64" ]
then
  >&2 echo "$(date +%D) $(date +%T) ERROR only supports 64-bit"
  exit 1
fi

if ! command -v brew &> /dev/null
then
  >&2 echo "$(date +%D) $(date +%T) ERROR brew command not found"
  exit 1
fi

brew install neovim

if ! command -v nvim &> /dev/null
then
  >&2 echo "$(date +%D) $(date +%T) ERROR neovim failed to installed"
  exit 1
fi

if [ -f "$HOME/.vimrc" ]
then
  >&2 echo "$(date +%D) $(date +%T) INFO there is no $HOME/.vimrc file"
else
  echo "source $HOME/.vimrc" >> "$HOME/.config/init.vim"

  if [ -f "$HOME/.config/init.vim" ]
  then
    >&2 echo "$(date +%D) $(date +%T) ERROR failed to create $HOME/.config/init.vim"
    exit 1
  elif ! grep -qE "source\s.+\.vimrc" "$HOME/.config/init.vim"
  then
    >&2 echo "$(date +%D) $(date +%T) ERROR failed to add source $HOME/.vimrc to $HOME/.config/init.vim"
    exit 1
  fi
fi

exit 0
