#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <environment>"
  exit 1
fi

ENV_ACCESS_TOKEN_NAME="ENV_${1^^}_ACCESS_TOKEN"

if [ -z "${!ENV_ACCESS_TOKEN_NAME}" ]
then
    echo "Cannot add $1.env because $ENV_ACCESS_TOKEN_NAME is not set"
    exit 1
fi

SOURCE_DIR="$(dirname "$(realpath "$0")")"

mkdir -p $SOURCE_DIR/private_environments
cd $SOURCE_DIR/private_environments

if [ -d "$1".env ]
then
    rm -rf "$1".env
fi

git clone "https://$GITHUB_USER:${!ENV_ACCESS_TOKEN_NAME}@github.com/$GITHUB_USER/$1.env.git"

$SOURCE_DIR/private_environments/$1.env/script/bootstrap

echo "export ENV_${$1^^}='$SOURCE_DIR/private_environments/$1.env'" >> ~/.bashrc
