#!/bin/bash

if [ -z $PRIVATE_ENV_ACCESS ]
then
    echo "Cannot add $1.env because PRIVATE_ENV_ACCESS is not set"
    exit 1
fi

SOURCE_DIR="$(dirname "$(realpath "$0")")"

mkdir -p $SOURCE_DIR/private_environments
cd $SOURCE_DIR/private_environments

if [ -d "$1".env ]
then
    rm -rf "$1".env
fi

git clone "https://$GITHUB_USER:$PRIVATE_ENV_ACCESS@github.com/$GITHUB_USER/$1.env.git"

$SOURCE_DIR/private_environments/$1.env/script/bootstrap
